<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IndustrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $industries = [
            'accounting',
            'advertising',
            'aerospace',
            'agriculture',
            'apparel_fashion',
            'architecture',
            'arts_crafts',
            'automotive',
            'aviation',
            'banking',
            'biotechnology',
            'broadcast_media',
            'building_materials',
            'business_supplies',
            'capital_markets',
            'chemicals',
            'civic_social_org',
            'civil_engineering',
            'commercial_real_estate',
            'computer_network_security',
            'computer_games',
            'computer_hardware',
            'computer_networking',
            'computer_software',
            'construction',
            'consumer_electronics',
            'consumer_goods',
            'consumer_services',
            'cosmetics',
            'dairy',
            'defense_space',
            'design',
            'e_learning',
            'education_management',
            'electrical_mfg',
            'entertainment',
            'environmental_services',
            'events_services',
            'executive_office',
            'facilities_services',
            'farming',
            'financial_services',
            'fine_art',
            'fishery',
            'food_beverages',
            'food_production',
            'fundraising',
            'furniture',
            'gambling_casinos',
            'glass_ceramics',
            'government_admin',
            'graphic_design',
            'health_wellness',
            'higher_education',
            'hospital_healthcare',
            'hospitality',
            'human_resources',
            'import_export',
            'family_services',
            'industrial_automation',
            'information_services',
            'it_services',
            'insurance',
            'international_affairs',
            'internet',
            'investment_banking',
            'judiciary',
            'law_enforcement',
            'law_practice',
            'legal_services',
            'logistics_supply',
            'luxury_goods',
            'consulting',
            'manufacturing',
            'marketing_advertising',
            'mechanical_engineering',
            'media_production',
            'medical_devices',
            'medical_practice',
            'mental_health',
            'military',
            'mining_metals',
            'film',
            'museums',
            'music',
            'nanotechnology',
            'newspapers',
            'non_profit',
            'oil_energy',
            'online_publishing',
            'outsourcing',
            'freight_delivery',
            'pharmaceuticals',
            'photography',
            'plastics',
            'political_org',
            'primary_secondary_edu',
            'printing',
            'training_coaching',
            'program_dev',
            'public_policy',
            'public_relations',
            'public_safety',
            'publishing',
            'real_estate',
            'recreation_services',
            'religious_institutions',
            'renewables',
            'research',
            'restaurants',
            'retail',
            'security_investigations',
            'semiconductors',
            'shipbuilding',
            'sports',
            'staffing',
            'supermarkets',
            'telecom',
            'textiles',
            'think_tanks',
            'tobacco',
            'translation',
            'transportation',
            'utilities',
            'venture_capital',
            'veterinary',
            'warehousing',
            'wholesale',
            'wine_spirits',
            'wireless',
            'writing_editing',
            'startup',
            'student',
            'other',
        ];


        DB::table('industries')->insert(
            collect($industries)->map(fn($name) => [
                'name' => $name,
                'created_at' => $now,
                'updated_at' => $now,
            ])->toArray()
        );
    }
}
